// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Q5ZMZvv1C0tTwRPXft3wl7BlBTXpfcA',
    appId: '1:483607190618:web:b02647b35c78978bd10c63',
    messagingSenderId: '483607190618',
    projectId: 'project-lambdadent',
    authDomain: 'project-lambdadent.firebaseapp.com',
    storageBucket: 'project-lambdadent.appspot.com',
    measurementId: 'G-9NNLER6L8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGXHyPSSRSoH4pwypSWtIa03v-FDVmo9A',
    appId: '1:483607190618:android:a6e13abb037958d7d10c63',
    messagingSenderId: '483607190618',
    projectId: 'project-lambdadent',
    storageBucket: 'project-lambdadent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgL8eb3lult8U9eW_hedMF0RIe6zeplR8',
    appId: '1:483607190618:ios:cc5c536978dab820d10c63',
    messagingSenderId: '483607190618',
    projectId: 'project-lambdadent',
    storageBucket: 'project-lambdadent.appspot.com',
    iosBundleId: 'com.example.flutterApplication3Getx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgL8eb3lult8U9eW_hedMF0RIe6zeplR8',
    appId: '1:483607190618:ios:cc5c536978dab820d10c63',
    messagingSenderId: '483607190618',
    projectId: 'project-lambdadent',
    storageBucket: 'project-lambdadent.appspot.com',
    iosBundleId: 'com.example.flutterApplication3Getx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Q5ZMZvv1C0tTwRPXft3wl7BlBTXpfcA',
    appId: '1:483607190618:web:1f7befa11d005c07d10c63',
    messagingSenderId: '483607190618',
    projectId: 'project-lambdadent',
    authDomain: 'project-lambdadent.firebaseapp.com',
    storageBucket: 'project-lambdadent.appspot.com',
    measurementId: 'G-3ZS4Q2NNJJ',
  );
}
